import { ClerkProvider } from "@clerk/nextjs";
import LBar from "@components/LBar";
import Nav from "@components/Nav";
import { Raleway } from "next/font/google";
import "@styles/globals.css";
export const metadata = {
  title: "TechShed-Products",
  description: "Generated by Next.js",
};
const raleway = Raleway({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${raleway.className} bg-[#fff]`}>
          <Nav />
          <LBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
