import "@styles/globals.css";
import { Raleway } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Arcade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${raleway.className} bg-[#edecec]`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
